kind: pipeline
type: docker
name: default

steps:
  - name: compile
    image: openjdk:17
    commands:
      - javac -d out src/**/*.java   # 编译所有 Java 源文件到指定的输出目录 (out)
      
  - name: run
    image: openjdk:17
    commands:
      - java -cp out Main            # 运行编译后的 Java 程序，假设主类是 Main
      
  - name: test
    image: openjdk:17
    commands:
      - java -cp out org.junit.runner.JUnitCore YourTestClass  # 运行测试类，假设你使用 JUnit 进行测试

  - name: package
    image: openjdk:17
    commands:
      - jar cvf your-app.jar -C out/ .  # 将编译后的类文件打包成 JAR 文件
